/* tslint:disable */
/* eslint-disable */
/**
 * Yadro Impulse Test Task
 * The goal of this task is to implement REST API and SPA to cover the described OpenAPI specification. Any Go library or frontend framework is acceptable. You may use https://editor.swagger.io to preview this spec.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: edu@yadro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

